[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[context.production]
  ignore = "git diff --quiet HEAD^ HEAD -- . ':(exclude)subscribers.json'"
